In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from matplotlib_inline import backend_inline
backend_inline.set_matplotlib_formats('svg')

In [3]:
device='mps'

In [4]:
X1=torch.rand(10000,1)
X2=torch.rand(10000,1)
X3=torch.rand(10000,1)
X1.shape, X2.shape, X3.shape

(torch.Size([10000, 1]), torch.Size([10000, 1]), torch.Size([10000, 1]))

In [5]:
Y1=((X1+X2+X3)<1).float()
Y2=((1<(X1+X2+X3))&(X1+X2+X3<2)).float()
Y3=((X1+X2+X3)>2).float()
Y1.shape, Y2.shape, Y3.shape

(torch.Size([10000, 1]), torch.Size([10000, 1]), torch.Size([10000, 1]))

In [6]:
Data=torch.cat([X1,X2,X3,Y1,Y2,Y3],axis=1)
Data=Data.to(device)
Data.shape

torch.Size([10000, 6])

In [7]:
Data

tensor([[0.0969, 0.4501, 0.8255, 0.0000, 1.0000, 0.0000],
        [0.6179, 0.1887, 0.9467, 0.0000, 1.0000, 0.0000],
        [0.1225, 0.3412, 0.4293, 1.0000, 0.0000, 0.0000],
        ...,
        [0.0864, 0.8588, 0.5325, 0.0000, 1.0000, 0.0000],
        [0.0610, 0.8492, 0.6290, 0.0000, 1.0000, 0.0000],
        [0.1512, 0.4931, 0.9120, 0.0000, 1.0000, 0.0000]], device='mps:0')

In [8]:
train_size=int(len(Data)*0.7)
test_size=len(Data)-train_size
Data=Data[torch.randperm(Data.size(0)) , : ]
train_Data=Data[:train_size, :]
test_Data=Data[train_size:, :]
train_Data.shape, test_Data.shape

(torch.Size([7000, 6]), torch.Size([3000, 6]))

In [9]:
class DNN(nn.Module):
    def __init__(self):
        super(DNN,self).__init__()
        self.net=nn.Sequential(
            nn.Linear(3,5), nn.ReLU(),
            nn.Linear(5,5), nn.ReLU(),
            nn.Linear(5,5), nn.ReLU(),
            nn.Linear(5,3)
        )
    def forward(self,x):
        y=self.net(x)
        return y

In [11]:
model=DNN().to(device)
model

DNN(
  (net): Sequential(
    (0): Linear(in_features=3, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=5, bias=True)
    (3): ReLU()
    (4): Linear(in_features=5, out_features=5, bias=True)
    (5): ReLU()
    (6): Linear(in_features=5, out_features=3, bias=True)
  )
)

In [13]:
for name,param in model.named_parameters():
    print(name, param.shape, param)

net.0.weight torch.Size([5, 3]) Parameter containing:
tensor([[ 0.3338, -0.5089, -0.5751],
        [ 0.5458,  0.3465, -0.4122],
        [-0.1984,  0.3979,  0.1012],
        [-0.5468, -0.0063, -0.4383],
        [ 0.3804,  0.0072,  0.1604]], device='mps:0', requires_grad=True)
net.0.bias torch.Size([5]) Parameter containing:
tensor([-0.0557, -0.4292, -0.0511,  0.4695,  0.4626], device='mps:0',
       requires_grad=True)
net.2.weight torch.Size([5, 5]) Parameter containing:
tensor([[ 0.2518,  0.1623,  0.0570,  0.2966,  0.3127],
        [-0.2685,  0.2155, -0.3212, -0.2557,  0.1334],
        [-0.1620, -0.1843, -0.3236,  0.3134, -0.0767],
        [-0.1405, -0.2952, -0.4137, -0.0378,  0.4022],
        [ 0.1515,  0.2509,  0.1378,  0.1254,  0.4134]], device='mps:0',
       requires_grad=True)
net.2.bias torch.Size([5]) Parameter containing:
tensor([-3.8987e-01, -4.0033e-01, -1.1361e-04,  4.0793e-01,  2.5819e-01],
       device='mps:0', requires_grad=True)
net.4.weight torch.Size([5, 5]) Paramet